version: "3.7"
networks: 
  proxy:
services:
  web:
    build: 
      context: ./web
      dockerfile: docker/Dockerfile
    volumes: 
      - ./web:/app/services/web
    networks:
      - proxy
  api: 
    build: 
      context: ./api
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/app/services/api
    networks:
      - proxy   
  reverse-proxy: 
    build: 
      context: ./reverse-proxy
      dockerfile: docker/Dockerfile
    ports: 
      - "80:80"
    depends_on: 
      - web
      - api
    networks: 
      - proxy