version: "3.7"

services:
  web:
    build: 
      context: ./web
      dockerfile: docker/Dockerfile
    volumes: 
      - ./web:/app/services/web
  reverse-proxy: 
    build: 
      context: ./reverse-proxy
      dockerfile: docker/Dockerfile
    ports: 
      - "80:80"
    depends_on: 
      - web